import { useState, useEffect } from 'react';
import { 
  AlertCircle, 
  ArrowRight,
  Sparkles,
  Clock,
  CheckCircle2,
  Activity,
  Network,
  Bot,
  Zap,
  ShieldAlert,
  Briefcase,
  ChevronRight,
  BarChart3
} from 'lucide-react';
import { 
  nextBestActions,
  aiBriefing,
  aiFeed,
  approvalWorkflows,
  revenueImpactMetrics,
  agentCollaborationFlow,
  executiveSummary
} from '../data/mockData';

const CommandCentre = () => {
  const [toastMessage, setToastMessage] = useState('');
  const [pulse, setPulse] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => setPulse(p => !p), 2000);
    return () => clearInterval(interval);
  }, []);

  const triggerAction = (actionName) => {
    setToastMessage(`Action triggered: ${actionName}`);
    setTimeout(() => setToastMessage(''), 3000);
  };

  return (
    <div className="cockpit-container">
      {toastMessage && (
        <div className="toast-notification">
          <CheckCircle2 size={18} />
          {toastMessage}
        </div>
      )}

      <div className="cockpit-header flex-between">
        <div className="header-text">
          <h1>Command Centre</h1>
          <p>AI-powered operational intelligence & lifecycle orchestration.</p>
        </div>
        <div className="live-status-badge">
          <span className="pulse-dot-green"></span>
          System Active
        </div>
      </div>

      {/* 1. AI DAILY EXECUTIVE BRIEFING */}
      <section className="executive-briefing-hero">
        <div className="hero-glow-bg"></div>
        <div className="eb-header">
          <div className="eb-title-group">
            <Sparkles size={24} className="text-accent" />
            <h2>Daily Executive Briefing</h2>
          </div>
          <div className="eb-generator">
            <Bot size={14} /> Generated by <span>Insight Narrator Agent</span>
          </div>
        </div>
        
        <div className="eb-content-grid">
          <div className="eb-narrative">
            <ul>
              {aiBriefing.narrative.map((item, idx) => (
                <li key={idx}><ChevronRight size={16} className="text-muted"/> {item}</li>
              ))}
            </ul>
          </div>
          <div className="eb-metrics">
            <div className="eb-metric-box">
              <span className="eb-label">Est. Opportunity</span>
              <span className="eb-value text-success">{aiBriefing.estimatedOpp}</span>
            </div>
            <div className="eb-metric-box">
              <span className="eb-label">Highest Priority</span>
              <span className="eb-value">{aiBriefing.priorityCohort}</span>
            </div>
            <div className="eb-metric-box">
              <span className="eb-label text-warning">Highest Risk</span>
              <span className="eb-value">{aiBriefing.highestRisk}</span>
            </div>
            <div className="eb-metric-box">
              <span className="eb-label">AI Confidence</span>
              <span className="eb-value text-accent">{aiBriefing.confidence}</span>
            </div>
          </div>
        </div>
      </section>

      {/* 5. REVENUE IMPACT OVERVIEW */}
      <section className="revenue-impact-section mt-48">
        <div className="revenue-grid">
          <div className="revenue-card">
            <span className="rc-label">Identified Today</span>
            <span className="rc-value text-success">{revenueImpactMetrics.identifiedToday}</span>
            <span className="rc-context">AI Confidence Range: 88-94%</span>
          </div>
          <div className="revenue-card">
            <span className="rc-label">Referral Projected</span>
            <span className="rc-value">{revenueImpactMetrics.referralProjected}</span>
            <span className="rc-context">Generated by Referral Agent</span>
          </div>
          <div className="revenue-card">
            <span className="rc-label">Recoverable Churn</span>
            <span className="rc-value text-warning">{revenueImpactMetrics.recoverableChurn}</span>
            <span className="rc-context">Generated by Retention Risk Agent</span>
          </div>
          <div className="revenue-card">
            <span className="rc-label">Conversion Uplift</span>
            <span className="rc-value text-success">{revenueImpactMetrics.conversionImprovement}</span>
            <span className="rc-context">vs. trailing 30 days</span>
          </div>
        </div>
      </section>

      <div className="split-layout mt-48">
        {/* LEFT COLUMN - MAIN OPERATIONS */}
        <div className="column-main">
          
          {/* 3. PRIORITY ACTIONS PANEL */}
          <section className="priority-actions-section">
            <div className="section-head">
              <div className="head-title">
                <Zap size={20} className="text-warning" />
                <h2>Priority Actions</h2>
              </div>
              <span className="ai-badge">Human-in-the-Loop</span>
            </div>
            
            <div className="pa-list">
              {nextBestActions.map(action => (
                <div key={action.id} className="pa-card elevated-card">
                  <div className="pa-card-header">
                    <h3 className="pa-title">{action.title}</h3>
                    <div className="pa-agent-tag">
                      <Bot size={12}/> {action.agent}
                    </div>
                  </div>
                  
                  <div className="pa-body">
                    <div className="pa-reasoning">
                      <span className="pa-label">Why:</span>
                      <p>{action.reasoning}</p>
                    </div>
                    
                    <div className="pa-metrics-row">
                      <div className="pa-m-item">
                        <span className="pa-label">Impact:</span>
                        <span className="text-success font-semibold">{action.impact} ({action.impactValue})</span>
                      </div>
                      <div className="pa-m-item">
                        <span className="pa-label">Confidence:</span>
                        <span className="text-accent font-semibold">{action.confidence}</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="pa-footer">
                    <button className="btn-primary-action" onClick={() => triggerAction(action.actionText)}>
                      {action.actionText} <ArrowRight size={14} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 6. HUMAN APPROVAL WORKFLOW PANEL */}
          <section className="approval-workflow-section mt-48">
            <div className="section-head">
              <div className="head-title">
                <Briefcase size={20} className="text-accent" />
                <h2>Awaiting Human Approval</h2>
              </div>
            </div>
            <div className="approval-list elevated-card">
              {approvalWorkflows.map(workflow => (
                <div key={workflow.id} className="approval-item">
                  <div className="app-info">
                    <h4>{workflow.action}</h4>
                    <span className="app-impact text-success">{workflow.impact}</span>
                  </div>
                  <div className="app-meta">
                    <span className="app-agent"><Bot size={12}/> {workflow.agent}</span>
                    <button className="btn-outline-approve" onClick={() => triggerAction('Approved Workflow')}>
                      Review & Approve
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 7. CROSS-AGENT COLLABORATION TIMELINE */}
          <section className="collaboration-timeline-section mt-48">
            <div className="section-head">
              <div className="head-title">
                <Network size={20} className="text-muted" />
                <h2>Intelligence Collaboration Flow</h2>
              </div>
            </div>
            <div className="timeline-container elevated-card">
              {agentCollaborationFlow.map((step, index) => (
                <div key={step.id} className="timeline-step">
                  <div className="ts-node">
                    <div className={`ts-dot ${index === agentCollaborationFlow.length -1 ? 'final' : ''}`}></div>
                    {index < agentCollaborationFlow.length - 1 && <div className="ts-line"></div>}
                  </div>
                  <div className="ts-content">
                    <span className="ts-agent">{step.agent}</span>
                    <span className="ts-action">{step.action}</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
          
          {/* 4. OPPORTUNITY & RISK RADAR */}
          <section className="radar-section mt-48">
             <div className="section-head">
              <div className="head-title">
                <ShieldAlert size={20} className="text-muted" />
                <h2>Opportunity & Risk Radar</h2>
              </div>
            </div>
            <div className="radar-grid">
              <div className="radar-item opp elevated-card">
                <span className="r-label">Top Opportunity</span>
                <span className="r-value">RMIT Final-Year Students</span>
              </div>
              <div className="radar-item risk elevated-card">
                <span className="r-label">Highest Churn Risk</span>
                <span className="r-value">Inactive New Arrivals</span>
              </div>
              <div className="radar-item growth elevated-card">
                <span className="r-label">Fastest Referral Growth</span>
                <span className="r-value">Monash Ambassadors</span>
              </div>
              <div className="radar-item alert elevated-card">
                <span className="r-label">Lowest Activation</span>
                <span className="r-value">OTP Failure Cohort</span>
              </div>
            </div>
          </section>

        </div>

        {/* RIGHT COLUMN - LIVE FEED */}
        <div className="column-side">
          
          {/* 2. LIVE AI AGENT ACTIVITY FEED */}
          <section className="live-feed-section">
            <div className="section-head">
              <div className="head-title">
                <Activity size={20} className="text-accent" />
                <h2>Live Agent Activity</h2>
              </div>
              <div className={`pulse-indicator ${pulse ? 'active' : ''}`}>
                <span className="dot"></span> Live
              </div>
            </div>
            
            <div className="feed-list">
              {aiFeed.map(feed => (
                <div key={feed.id} className="feed-card elevated-card">
                  <div className="fc-header">
                    <span className="fc-agent"><Bot size={12}/> {feed.agent}</span>
                    <span className="fc-time">{feed.time}</span>
                  </div>
                  <p className="fc-insight">{feed.insight}</p>
                  <div className="fc-footer">
                    <span className={`fc-impact ${feed.impact.includes('-') ? 'text-warning' : 'text-success'}`}>{feed.impact}</span>
                    <span className="fc-confidence">{feed.confidence} conf.</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
          
        </div>
      </div>

      {/* 8. EXECUTIVE STRATEGIC SUMMARY */}
      <section className="executive-summary-section mt-48 elevated-card">
        <div className="es-icon">
          <BarChart3 size={24} className="text-accent" />
        </div>
        <div className="es-content">
          <span className="es-label">Strategic Summary · Generated by Insight Narrator</span>
          <p className="es-text">"{executiveSummary}"</p>
        </div>
      </section>

      <style>{`
        /* 
          LINEAR / STRIPE INSPIRED DARK THEME
          High contrast, deep blacks, subtle gradients, crisp typography
        */
        
        .cockpit-container {
          --bg-dark: #0A0A0B;
          --card-bg: #121316;
          --card-border: rgba(255, 255, 255, 0.06);
          --card-border-hover: rgba(255, 255, 255, 0.12);
          
          --text-bright: #FFFFFF;
          --text-main: #E2E8F0;
          --text-muted: #8B949E;
          
          --medibank-red: #E60028;
          --medibank-red-hover: #FF1A43;
          
          --color-success: #10B981;
          --color-warning: #F5A623;
          --color-danger: #EF4444;
          --color-accent: #3B82F6;
          --color-accent-glow: rgba(59, 130, 246, 0.15);

          color: var(--text-main);
          padding-bottom: 80px;
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }

        .mt-48 { margin-top: 48px; }
        .text-bright { color: var(--text-bright); font-weight: 500; }
        .text-muted { color: var(--text-muted); }
        .text-warning { color: var(--color-warning); }
        .text-danger { color: var(--color-danger); }
        .text-success { color: var(--color-success); }
        .text-accent { color: var(--color-accent); }
        .font-semibold { font-weight: 600; }

        h1, h2, h3, h4 { color: var(--text-bright); letter-spacing: -0.02em; margin:0; }
        
        .cockpit-header { margin-bottom: 40px; }
        .header-text h1 { font-size: 32px; font-weight: 700; margin-bottom: 8px; }
        .header-text p { font-size: 15px; color: var(--text-muted); }
        
        .live-status-badge {
          display: flex; align-items: center; gap: 8px;
          background: rgba(16, 185, 129, 0.1);
          color: var(--color-success);
          padding: 6px 12px; border-radius: 20px;
          font-size: 13px; font-weight: 600;
          border: 1px solid rgba(16, 185, 129, 0.2);
        }
        .pulse-dot-green {
          width: 8px; height: 8px; border-radius: 50%; background: var(--color-success);
          box-shadow: 0 0 10px var(--color-success); animation: pulse 2s infinite;
        }

        .section-head {
          display: flex; justify-content: space-between; align-items: center;
          margin-bottom: 24px; padding-bottom: 12px;
          border-bottom: 1px solid rgba(255,255,255,0.04);
        }
        .head-title { display: flex; align-items: center; gap: 10px; }
        .head-title h2 { font-size: 18px; font-weight: 600; }

        .elevated-card {
          background: var(--card-bg);
          border: 1px solid var(--card-border);
          border-radius: 12px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.2), inset 0 1px 0 rgba(255,255,255,0.03);
          transition: all 0.2s ease;
        }
        .elevated-card:hover {
          border-color: var(--card-border-hover);
          box-shadow: 0 8px 24px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.05);
        }

        /* 1. Executive Briefing Hero */
        .executive-briefing-hero {
          position: relative;
          padding: 40px;
          border-radius: 16px;
          background: linear-gradient(180deg, #16181D 0%, #0F1115 100%);
          border: 1px solid rgba(255,255,255,0.08);
          overflow: hidden;
          box-shadow: 0 20px 40px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.1);
        }
        .hero-glow-bg {
          position: absolute; top: -50%; left: -10%; width: 120%; height: 200%;
          background: radial-gradient(circle at top left, var(--color-accent-glow), transparent 60%);
          pointer-events: none; z-index: 0;
        }
        .eb-header {
          position: relative; z-index: 1;
          display: flex; justify-content: space-between; align-items: flex-start;
          margin-bottom: 32px;
        }
        .eb-title-group { display: flex; align-items: center; gap: 12px; }
        .eb-title-group h2 { font-size: 24px; font-weight: 600; }
        .eb-generator {
          display: flex; align-items: center; gap: 6px;
          font-size: 12px; color: var(--text-muted);
          background: rgba(255,255,255,0.05); padding: 4px 12px; border-radius: 20px;
        }
        .eb-generator span { color: var(--text-main); font-weight: 500; }
        
        .eb-content-grid {
          position: relative; z-index: 1;
          display: grid; grid-template-columns: 1fr 1fr; gap: 40px;
        }
        .eb-narrative ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 16px; }
        .eb-narrative li {
          display: flex; align-items: flex-start; gap: 10px;
          font-size: 16px; line-height: 1.5; color: var(--text-bright);
        }
        
        .eb-metrics { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .eb-metric-box {
          background: rgba(0,0,0,0.2); border: 1px solid rgba(255,255,255,0.05);
          padding: 16px; border-radius: 10px;
          display: flex; flex-direction: column; gap: 6px;
        }
        .eb-label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--text-muted); font-weight: 600;}
        .eb-value { font-size: 20px; font-weight: 700; letter-spacing: -0.5px; }

        /* 5. Revenue Impact */
        .revenue-grid {
          display: grid; grid-template-columns: repeat(4, 1fr); gap: 24px;
        }
        .revenue-card {
          padding: 24px; background: transparent;
          border-left: 2px solid var(--card-border);
          display: flex; flex-direction: column; gap: 8px;
        }
        .rc-label { font-size: 14px; font-weight: 500; color: var(--text-muted); }
        .rc-value { font-size: 32px; font-weight: 700; letter-spacing: -1px; color: var(--text-bright); }
        .rc-context { font-size: 12px; color: var(--text-muted); }

        /* Layout Split */
        .split-layout { display: grid; grid-template-columns: 1.8fr 1fr; gap: 40px; }

        /* 3. Priority Actions */
        .ai-badge {
          background: rgba(59, 130, 246, 0.1); border: 1px solid rgba(59, 130, 246, 0.2);
          color: var(--color-accent); padding: 4px 10px; border-radius: 6px;
          font-size: 12px; font-weight: 600;
        }
        .pa-list { display: flex; flex-direction: column; gap: 20px; }
        .pa-card { padding: 24px; }
        .pa-card-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; }
        .pa-title { font-size: 18px; font-weight: 600; }
        .pa-agent-tag {
          display: flex; align-items: center; gap: 6px;
          font-size: 12px; background: rgba(255,255,255,0.05); padding: 4px 10px; border-radius: 6px; color: var(--text-muted);
        }
        
        .pa-body { margin-bottom: 24px; }
        .pa-reasoning { background: rgba(0,0,0,0.2); padding: 16px; border-radius: 8px; margin-bottom: 16px; border: 1px solid rgba(255,255,255,0.03); }
        .pa-label { font-size: 12px; text-transform: uppercase; color: var(--text-muted); font-weight: 600; margin-bottom: 4px; display: block; }
        .pa-reasoning p { font-size: 14px; color: var(--text-main); line-height: 1.5; margin: 0; }
        
        .pa-metrics-row { display: flex; gap: 32px; }
        .pa-m-item { display: flex; flex-direction: column; gap: 4px; }
        .pa-m-item span:last-child { font-size: 16px; }

        .btn-primary-action {
          display: inline-flex; align-items: center; justify-content: center; gap: 8px;
          background: var(--text-bright); color: var(--bg-dark);
          border: none; padding: 12px 24px; border-radius: 8px;
          font-size: 14px; font-weight: 600; cursor: pointer; transition: all 0.2s;
        }
        .btn-primary-action:hover { background: #E2E8F0; transform: translateY(-1px); box-shadow: 0 4px 12px rgba(255,255,255,0.1); }

        /* 6. Approval Workflow */
        .approval-list { padding: 8px 24px; }
        .approval-item {
          display: flex; justify-content: space-between; align-items: center;
          padding: 20px 0; border-bottom: 1px solid rgba(255,255,255,0.05);
        }
        .approval-item:last-child { border-bottom: none; }
        .app-info h4 { font-size: 15px; margin-bottom: 4px; }
        .app-impact { font-size: 13px; font-weight: 500; }
        .app-meta { display: flex; flex-direction: column; align-items: flex-end; gap: 10px; }
        .app-agent { display: flex; align-items: center; gap: 4px; font-size: 12px; color: var(--text-muted); }
        
        .btn-outline-approve {
          background: transparent; border: 1px solid var(--color-success); color: var(--color-success);
          padding: 6px 14px; border-radius: 6px; font-size: 12px; font-weight: 600; cursor: pointer;
          transition: all 0.2s;
        }
        .btn-outline-approve:hover { background: rgba(16, 185, 129, 0.1); }

        /* 7. Timeline */
        .timeline-container { padding: 32px 40px; }
        .timeline-step { display: flex; gap: 24px; }
        .ts-node { display: flex; flex-direction: column; align-items: center; }
        .ts-dot { width: 10px; height: 10px; border-radius: 50%; background: var(--text-muted); border: 2px solid var(--card-bg); z-index: 2; }
        .ts-dot.final { background: var(--color-accent); box-shadow: 0 0 10px var(--color-accent); }
        .ts-line { width: 2px; height: 40px; background: rgba(255,255,255,0.1); margin: -2px 0; }
        .ts-content { padding-bottom: 30px; display: flex; flex-direction: column; gap: 4px; transform: translateY(-4px); }
        .ts-agent { font-size: 12px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.5px; }
        .ts-action { font-size: 15px; color: var(--text-bright); }

        /* 4. Radar Grid */
        .radar-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        .radar-item { padding: 20px; display: flex; flex-direction: column; gap: 8px; border-left: 3px solid transparent; }
        .radar-item.opp { border-left-color: var(--color-success); }
        .radar-item.risk { border-left-color: var(--color-warning); }
        .radar-item.growth { border-left-color: var(--color-accent); }
        .radar-item.alert { border-left-color: var(--color-danger); }
        .r-label { font-size: 12px; color: var(--text-muted); text-transform: uppercase; font-weight: 600; }
        .r-value { font-size: 16px; font-weight: 600; color: var(--text-bright); }

        /* 2. Live Feed */
        .pulse-indicator { display: flex; align-items: center; gap: 6px; font-size: 12px; color: var(--text-muted); font-weight: 600; }
        .pulse-indicator .dot { width: 6px; height: 6px; border-radius: 50%; background: var(--text-muted); transition: all 0.3s; }
        .pulse-indicator.active .dot { background: var(--color-accent); box-shadow: 0 0 8px var(--color-accent); }
        .pulse-indicator.active { color: var(--color-accent); }

        .feed-list { display: flex; flex-direction: column; gap: 16px; }
        .feed-card { padding: 16px; }
        .fc-header { display: flex; justify-content: space-between; margin-bottom: 8px; }
        .fc-agent { display: flex; align-items: center; gap: 4px; font-size: 12px; font-weight: 600; color: var(--text-muted); }
        .fc-time { font-size: 11px; color: var(--text-muted); }
        .fc-insight { font-size: 14px; line-height: 1.4; margin-bottom: 12px; color: var(--text-bright); }
        .fc-footer { display: flex; justify-content: space-between; font-size: 12px; font-weight: 500; }
        .fc-confidence { color: var(--text-muted); }

        /* 8. Executive Summary */
        .executive-summary-section {
          padding: 32px; display: flex; gap: 24px; align-items: flex-start;
          background: linear-gradient(90deg, rgba(59, 130, 246, 0.05) 0%, transparent 100%);
          border-left: 2px solid var(--color-accent);
        }
        .es-content { display: flex; flex-direction: column; gap: 8px; }
        .es-label { font-size: 12px; text-transform: uppercase; font-weight: 600; color: var(--text-muted); letter-spacing: 0.5px; }
        .es-text { font-size: 18px; font-weight: 400; line-height: 1.6; color: var(--text-bright); font-style: italic; margin: 0; }
        
        .toast-notification {
          position: fixed; bottom: 30px; right: 30px; z-index: 100;
          background: var(--text-bright); color: var(--bg-dark);
          padding: 12px 24px; border-radius: 8px; font-size: 14px; font-weight: 600;
          display: flex; align-items: center; gap: 10px;
          box-shadow: 0 10px 25px rgba(0,0,0,0.3);
          animation: slideUp 0.3s ease forwards;
        }

        @keyframes pulse {
          0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.7); }
          70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(16, 185, 129, 0); }
          100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(16, 185, 129, 0); }
        }
        
        @keyframes slideUp {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }

      `}</style>
    </div>
  );
};

export default CommandCentre;
